// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: .proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.transferclipboard.backend.protobuf;

@kotlin.jvm.JvmName("-initializeimageList")
public inline fun imageList(block: com.transferclipboard.backend.protobuf.ImageListKt.Dsl.() -> kotlin.Unit): com.transferclipboard.backend.protobuf.ProtobufData.ImageList =
  com.transferclipboard.backend.protobuf.ImageListKt.Dsl._create(com.transferclipboard.backend.protobuf.ProtobufData.ImageList.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `protobuf.ImageList`
 */
public object ImageListKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.transferclipboard.backend.protobuf.ProtobufData.ImageList.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.transferclipboard.backend.protobuf.ProtobufData.ImageList.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.transferclipboard.backend.protobuf.ProtobufData.ImageList = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ListProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .protobuf.Image list = 2;`
     */
     public val list: com.google.protobuf.kotlin.DslList<com.transferclipboard.backend.protobuf.ProtobufData.Image, ListProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getListList()
      )
    /**
     * `repeated .protobuf.Image list = 2;`
     * @param value The list to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addList")
    public fun com.google.protobuf.kotlin.DslList<com.transferclipboard.backend.protobuf.ProtobufData.Image, ListProxy>.add(value: com.transferclipboard.backend.protobuf.ProtobufData.Image) {
      _builder.addList(value)
    }
    /**
     * `repeated .protobuf.Image list = 2;`
     * @param value The list to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignList")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.transferclipboard.backend.protobuf.ProtobufData.Image, ListProxy>.plusAssign(value: com.transferclipboard.backend.protobuf.ProtobufData.Image) {
      add(value)
    }
    /**
     * `repeated .protobuf.Image list = 2;`
     * @param values The list to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllList")
    public fun com.google.protobuf.kotlin.DslList<com.transferclipboard.backend.protobuf.ProtobufData.Image, ListProxy>.addAll(values: kotlin.collections.Iterable<com.transferclipboard.backend.protobuf.ProtobufData.Image>) {
      _builder.addAllList(values)
    }
    /**
     * `repeated .protobuf.Image list = 2;`
     * @param values The list to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllList")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.transferclipboard.backend.protobuf.ProtobufData.Image, ListProxy>.plusAssign(values: kotlin.collections.Iterable<com.transferclipboard.backend.protobuf.ProtobufData.Image>) {
      addAll(values)
    }
    /**
     * `repeated .protobuf.Image list = 2;`
     * @param index The index to set the value at.
     * @param value The list to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setList")
    public operator fun com.google.protobuf.kotlin.DslList<com.transferclipboard.backend.protobuf.ProtobufData.Image, ListProxy>.set(index: kotlin.Int, value: com.transferclipboard.backend.protobuf.ProtobufData.Image) {
      _builder.setList(index, value)
    }
    /**
     * `repeated .protobuf.Image list = 2;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearList")
    public fun com.google.protobuf.kotlin.DslList<com.transferclipboard.backend.protobuf.ProtobufData.Image, ListProxy>.clear() {
      _builder.clearList()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.transferclipboard.backend.protobuf.ProtobufData.ImageList.copy(block: com.transferclipboard.backend.protobuf.ImageListKt.Dsl.() -> kotlin.Unit): com.transferclipboard.backend.protobuf.ProtobufData.ImageList =
  com.transferclipboard.backend.protobuf.ImageListKt.Dsl._create(this.toBuilder()).apply { block() }._build()

