// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: .proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.transferclipboard.backend.protobuf;

@kotlin.jvm.JvmName("-initializeonlineUsers")
public inline fun onlineUsers(block: com.transferclipboard.backend.protobuf.OnlineUsersKt.Dsl.() -> kotlin.Unit): com.transferclipboard.backend.protobuf.ProtobufData.OnlineUsers =
  com.transferclipboard.backend.protobuf.OnlineUsersKt.Dsl._create(com.transferclipboard.backend.protobuf.ProtobufData.OnlineUsers.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `protobuf.OnlineUsers`
 */
public object OnlineUsersKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.transferclipboard.backend.protobuf.ProtobufData.OnlineUsers.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.transferclipboard.backend.protobuf.ProtobufData.OnlineUsers.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.transferclipboard.backend.protobuf.ProtobufData.OnlineUsers = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class UsersProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string users = 1;`
     * @return A list containing the users.
     */
    public val users: com.google.protobuf.kotlin.DslList<kotlin.String, UsersProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getUsersList()
      )
    /**
     * `repeated string users = 1;`
     * @param value The users to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addUsers")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, UsersProxy>.add(value: kotlin.String) {
      _builder.addUsers(value)
    }
    /**
     * `repeated string users = 1;`
     * @param value The users to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignUsers")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, UsersProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string users = 1;`
     * @param values The users to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllUsers")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, UsersProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllUsers(values)
    }
    /**
     * `repeated string users = 1;`
     * @param values The users to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllUsers")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, UsersProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string users = 1;`
     * @param index The index to set the value at.
     * @param value The users to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setUsers")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, UsersProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setUsers(index, value)
    }/**
     * `repeated string users = 1;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearUsers")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, UsersProxy>.clear() {
      _builder.clearUsers()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun com.transferclipboard.backend.protobuf.ProtobufData.OnlineUsers.copy(block: com.transferclipboard.backend.protobuf.OnlineUsersKt.Dsl.() -> kotlin.Unit): com.transferclipboard.backend.protobuf.ProtobufData.OnlineUsers =
  com.transferclipboard.backend.protobuf.OnlineUsersKt.Dsl._create(this.toBuilder()).apply { block() }._build()

