// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: .proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.transferclipboard.backend.protobuf;

@kotlin.jvm.JvmName("-initializetransferData")
public inline fun transferData(block: com.transferclipboard.backend.protobuf.TransferDataKt.Dsl.() -> kotlin.Unit): com.transferclipboard.backend.protobuf.ProtobufData.TransferData =
  com.transferclipboard.backend.protobuf.TransferDataKt.Dsl._create(com.transferclipboard.backend.protobuf.ProtobufData.TransferData.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `protobuf.TransferData`
 */
public object TransferDataKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.transferclipboard.backend.protobuf.ProtobufData.TransferData.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.transferclipboard.backend.protobuf.ProtobufData.TransferData.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.transferclipboard.backend.protobuf.ProtobufData.TransferData = _builder.build()

    /**
     * `string fromuid = 1;`
     */
    public var fromuid: kotlin.String
      @JvmName("getFromuid")
      get() = _builder.getFromuid()
      @JvmName("setFromuid")
      set(value) {
        _builder.setFromuid(value)
      }
    /**
     * `string fromuid = 1;`
     */
    public fun clearFromuid() {
      _builder.clearFromuid()
    }

    /**
     * `string touid = 2;`
     */
    public var touid: kotlin.String
      @JvmName("getTouid")
      get() = _builder.getTouid()
      @JvmName("setTouid")
      set(value) {
        _builder.setTouid(value)
      }
    /**
     * `string touid = 2;`
     */
    public fun clearTouid() {
      _builder.clearTouid()
    }

    /**
     * `.protobuf.TransferData.DataType type = 3;`
     */
    public var type: com.transferclipboard.backend.protobuf.ProtobufData.TransferData.DataType
      @JvmName("getType")
      get() = _builder.getType()
      @JvmName("setType")
      set(value) {
        _builder.setType(value)
      }
    public var typeValue: kotlin.Int
      @JvmName("getTypeValue")
      get() = _builder.getTypeValue()
      @JvmName("setTypeValue")
      set(value) {
        _builder.setTypeValue(value)
      }
    /**
     * `.protobuf.TransferData.DataType type = 3;`
     */
    public fun clearType() {
      _builder.clearType()
    }

    /**
     * `.protobuf.Text text = 4;`
     */
    public var text: com.transferclipboard.backend.protobuf.ProtobufData.Text
      @JvmName("getText")
      get() = _builder.getText()
      @JvmName("setText")
      set(value) {
        _builder.setText(value)
      }
    /**
     * `.protobuf.Text text = 4;`
     */
    public fun clearText() {
      _builder.clearText()
    }
    /**
     * `.protobuf.Text text = 4;`
     * @return Whether the text field is set.
     */
    public fun hasText(): kotlin.Boolean {
      return _builder.hasText()
    }

    /**
     * `.protobuf.Image image = 5;`
     */
    public var image: com.transferclipboard.backend.protobuf.ProtobufData.Image
      @JvmName("getImage")
      get() = _builder.getImage()
      @JvmName("setImage")
      set(value) {
        _builder.setImage(value)
      }
    /**
     * `.protobuf.Image image = 5;`
     */
    public fun clearImage() {
      _builder.clearImage()
    }
    /**
     * `.protobuf.Image image = 5;`
     * @return Whether the image field is set.
     */
    public fun hasImage(): kotlin.Boolean {
      return _builder.hasImage()
    }

    /**
     * `.protobuf.File file = 6;`
     */
    public var file: com.transferclipboard.backend.protobuf.ProtobufData.File
      @JvmName("getFile")
      get() = _builder.getFile()
      @JvmName("setFile")
      set(value) {
        _builder.setFile(value)
      }
    /**
     * `.protobuf.File file = 6;`
     */
    public fun clearFile() {
      _builder.clearFile()
    }
    /**
     * `.protobuf.File file = 6;`
     * @return Whether the file field is set.
     */
    public fun hasFile(): kotlin.Boolean {
      return _builder.hasFile()
    }

    /**
     * `string notification = 7;`
     */
    public var notification: kotlin.String
      @JvmName("getNotification")
      get() = _builder.getNotification()
      @JvmName("setNotification")
      set(value) {
        _builder.setNotification(value)
      }
    /**
     * `string notification = 7;`
     */
    public fun clearNotification() {
      _builder.clearNotification()
    }
    /**
     * `string notification = 7;`
     * @return Whether the notification field is set.
     */
    public fun hasNotification(): kotlin.Boolean {
      return _builder.hasNotification()
    }

    /**
     * `string error = 8;`
     */
    public var error: kotlin.String
      @JvmName("getError")
      get() = _builder.getError()
      @JvmName("setError")
      set(value) {
        _builder.setError(value)
      }
    /**
     * `string error = 8;`
     */
    public fun clearError() {
      _builder.clearError()
    }
    /**
     * `string error = 8;`
     * @return Whether the error field is set.
     */
    public fun hasError(): kotlin.Boolean {
      return _builder.hasError()
    }
    public val dataCase: com.transferclipboard.backend.protobuf.ProtobufData.TransferData.DataCase
      @JvmName("getDataCase")
      get() = _builder.getDataCase()

    public fun clearData() {
      _builder.clearData()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.transferclipboard.backend.protobuf.ProtobufData.TransferData.copy(block: com.transferclipboard.backend.protobuf.TransferDataKt.Dsl.() -> kotlin.Unit): com.transferclipboard.backend.protobuf.ProtobufData.TransferData =
  com.transferclipboard.backend.protobuf.TransferDataKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.transferclipboard.backend.protobuf.ProtobufData.TransferDataOrBuilder.textOrNull: com.transferclipboard.backend.protobuf.ProtobufData.Text?
  get() = if (hasText()) getText() else null

public val com.transferclipboard.backend.protobuf.ProtobufData.TransferDataOrBuilder.imageOrNull: com.transferclipboard.backend.protobuf.ProtobufData.Image?
  get() = if (hasImage()) getImage() else null

public val com.transferclipboard.backend.protobuf.ProtobufData.TransferDataOrBuilder.fileOrNull: com.transferclipboard.backend.protobuf.ProtobufData.File?
  get() = if (hasFile()) getFile() else null

